name: CI Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v3

      - name: Test simple
        run: echo "Mon CI fonctionne"
